### ISSUE TITLE
Latest Master won't compile - fcurrentPosition not declared in this scope

### ISSUE THREAD

**Issue by hcomet** [brownrb/myFP2EFirmware#18]
myFP2ESP:469:22: error: 'fcurrentPosition' was not declared in this scope
       newpos = (long)fcurrentPosition + adjpos;
                      ^
myFP2ESP:475:16: error: 'fcurrentPosition' was not declared in this scope
       newpos = fcurrentPosition + adjpos;

Looks like fcurrentPosition is being deprecated and these lines were missed.

**Comment by brownrb** [comment]
Branch 133 created to apply fix
fcurrentposition is invalid: It should be using the value from mySetupData instead

**Comment by brownrb** [comment]
Issue has been addressed in branch 133, now merged back in master
