### ISSUE TITLE
Missing #define for IR_HALT in latest master

### ISSUE THREAD

**Issue by hcomet** [brownrb/myFP2EFirmware#24]
Tried to compile with IR Remote enabled and received:

myFP2ESP:352:42: error: 'IR_HALT' was not declared in this scope
     if ( (isMoving == 1) && (lastcode == IR_HALT))

Looks like the #define for IR_HALT is missing from irremotemappings.h. I added:

// Halt
#define IR_HALT         KEY_EIGHT

from the irremotemappings.h I have from sourcesforge and it compiled fine.

**Comment by brownrb** [comment]
Fixed. IR HALT definition added to irremotemapping.h file
